# Generated by Django 5.0.4 on 2024-05-29 13:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_category_cid_alter_product_pid_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="products_status",
            new_name="product_status",
        ),
        migrations.RemoveField(
            model_name="product",
            name="tags",
        ),
    ]
