# Generated by Django 5.0.4 on 2024-05-30 14:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_product_vendor"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.ImageField(default="category.jpg", upload_to="category"),
        ),
    ]
