# Generated by Django 5.0.4 on 2024-06-02 21:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_category_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendor",
            name="image",
            field=models.ImageField(default="vendor.jpg", upload_to="vendor"),
        ),
    ]
