# Generated by Django 5.0.4 on 2024-06-02 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_vendor_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="tags",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="core.tags"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="vendor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="product",
                to="core.vendor",
            ),
        ),
    ]
