# Generated by Django 5.0.4 on 2024-06-02 23:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_product_tags_alter_product_vendor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="tags",
        ),
    ]
