# Generated by Django 5.0.4 on 2024-07-22 18:56

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_remove_product_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="pid",
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet="abc12", length=22, max_length=5, prefix="", unique=True
            ),
        ),
    ]
